### ISSUE TITLE
[Proposal] Optimise queries with nested population.

### ISSUE THREAD

**Issue by mathieutu** [b1f6c1c4/graphql-advanced-projection#10]
Hi, 
I've seen in https://itnext.io/graphql-mongoose-a-design-first-approach-d97b7f0c869 how you handle nested, and ref relations.

Actually your way has some problems:

- Storing an array of children in a parent is quite an anti pattern: 
   - Your array and so your document will grow for nothing,
   - If you only want the children, you have to query the parent (for nothing), populate, and return only the `parent.children`.
   - And other explainations here: https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/#pattern

- Populate directly in nested resolvers:
   - You will have as many calls as many the nested resolver will be called, so for nested object, at least the number of parents. If you have nested of nested it can be really problematic (hundred of calls very quickly).
   - As you're returning directly the children, you don't need to populate at all, a _where in_ is enough.
   - We have to write all the resolvers by hand.

Solution: (yeah because, it's a proposal, I'm not here just to complain 😛)

- For the array of children, just put the parentId in child. No more growing array, no more need to populate. And in mongoose, you can define virtual with ref, and it will be exactly the same. See http://mongoosejs.com/docs/populate.html#populate-virtuals. 
But this one is for information and have no link with this package.

- For the nested resolvers: we have a way to do it muuuch better in my opinion.
Indeed, we can directly populate all the nested and subnested items directly in the first resolver, by writing the populate option with the help of projections !

I've made a bunch of functions to convert projections to a populate config object, and so I can query directly all the demanded item with: 

```ts
async campaigns(root, args, ctx, info) {
    const projections = project(info);
    const population = populate(projections);

    return Campaign.find({}, projections).populate(population);
},
```

And with that it will make the minimum number of queries to fetch all the needed documents. Example: 

Query:
```graphql
{
  campaigns {
    id
    title
    questions {
      id
      message
      answers {
        id
        value
      }
    }
  }
}
```

Mongoose requests done:
```js
campaigns.find({}, { fields: { id: 1, title: 1, 'questions.id': 1, 'questions.message': 1, 'questions.answers.id': 1, 'questions.answers.value': 1, questions: 1 } })
questions.find({ campaignId: { '$in': [ ObjectId("5b59b5c6a30e7b2b8d1ea74f"), ObjectId("5b59b719ad4dd22bbd62750b"), ObjectId("5b59b719ad4dd22bbdv2750b"), [length]: 3 ] } }, { fields: { id: 1, message: 1, answers: 1, campaignId: 1 } })
answers.find({ questionId: { '$in': [ ObjectId("5b5a439a935a0d32bc688f15"), ObjectId("5b5a439a935a0d32bc588f15", ObjectId("5b5a439a935a0d32bc698f15", [length]: 3 ] } }, { fields: { id: 1, value: 1, questionId: 1 } })
```

Here we have 3 levels asked, so 3 queries in any case.

With nested resolvers, we would have for this concrete case:
10 Campaigns: 1 query.
20 Questions by Campaign: 10 * 1 queries.
3 Answers by Questions: 10 * 20 * 1 queries.

About 200 queries, for only 3 levels. And it will grow with each document and each level added.

Are you interested by a PR with theses functions, and then write some documentation/update the article?

**Comment by b1f6c1c4** [comment]
#### Which MongoDB _structure to use_ when modeling one-to-many relationship?
Please do NOT presumptuously consider storing an array of children in a parent an anti-pattern - it IS an anti pattern when dealing with growing children, but IS NOT when dealing a fixed number of children. For example, in my bookkeeping project, a voucher has a *fixed* number of voucher details, and these details are usually accessed as a whole, so using nested docs *in this case* should be perfect for performance. However, for your application, refs may be better.

In general, `graphql-advanced-projection` aims to be applicable in most of the regular use cases.

#### If I use *refs*, how do I query more efficiently deeply-nested docs?

Speed and conciseness never meet. [My example](https://github.com/b1f6c1c4/graphql-advanced-projection/blob/master/examples/reference/index.js#L33-L46) opts for the brevity of the code (following the GraphQL logics: the parent resolver resolves the parent, while the child resolver resolves the children).

To instead opt for the speed of execution, one has to address everything in the `async user(parent, args, context, info)` function, by using your method above.

#### Should `graphql-advanced-projection` support automating that?

Good question. I'll think about it and come back later.

**Comment by mathieutu** [comment]
Hi, I think I didn't make me understood, I'm sorry. I'm not a native english speaker, and I will try to reformulate.

**Firstly, the structure** (which as no link with the package, but your article):

I never wrote about sub documents, but always about refs. 
Storing all the nested item in the parent document is a good pattern for many projects! I wasn't talking about that.

I was talking about storing in the parent an array of children ID as ref as described [here](https://docs.mongodb.com/manual/tutorial/model-tree-structures-with-child-references/) and why it could be an anti pattern. 

Even if you have a limited number of children, you often should better have to store a parentId in your children than the opposite.

It's a common way to do it, in relational architectures, not depending of the language, or the type of API.

Lets take a User/Post classic example:

Get all the Post of the User of _id=1.
```js 
// with ref in parent: 
const user = await User.findById(1);
return Post.find({ _id: { $in: user.postsId })

// with ref in children:
return Post.find({userId: 1})
```

Add a new Post to the User of _id=1 and return it.
```js 
// with ref in parent: 
const post = await new Post().save();
const user = await User.findById(1);
await user.postsId.push(post.id);
return post;

// with ref in children:
return new Post({userId: 1}).save();
```

Get the User of _id=1 with all this Posts and return it.
```js 
// with ref in parent: 
User.findById(1).populate('posts')

// with ref in children:
User.findById(1).populate('posts')
```

**Secondly, the optimization of nested queries in the package**
I've seen your PR and actually I didn't understand why it should fix this issue.

With what I've done, you can directly write:
```js
const { projections, populations } = parseInfo(info);
return Campaign.findById(id, projections).populate(populations);
```
and it's done, you have all your items and nested with only the demanded fields, and one unique query by nested level.

**I've made it** in typescript but **I can** modify it to js **and open a PR**, but I prefer to know that you want to implement it, just to avoid useless work 😅

Thanks anyway for your work, and your article. I'm discovering graphql, and I was not satisfied by the previously seen solutions, until I found your article (I was doing exactly the same thing on my own) !

**Comment by b1f6c1c4** [comment]
Talk is cheap, show me the code. Why not open a PR first in typescript? And discuss it directly, utilizing the powerful PR reviewing workflow by Github. 😅

**Comment by mathieutu** [comment]
My comments were not about code, but process and DX...

But I made the integration and added an example in #14.
